CREATE TABLE dog_image_urls
(
    dog_id    BIGINT NOT NULL,
    image_url VARCHAR(255)
);

CREATE TABLE dogs
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    breed      VARCHAR(255),
    created_at TIMESTAMP                               NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_dogs PRIMARY KEY (id)
);

ALTER TABLE dog_image_urls
    ADD CONSTRAINT fk_dog_image_urls_on_dogs FOREIGN KEY (dog_id) REFERENCES dogs (id);